version: 2
ethernets:
  ens2:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.5/24
      - fc00::5/64
    gateway4: 192.168.100.1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  ens3:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc50::2/64
    nameservers: {}
