version: 2
ethernets:
  lo:
    match:
      name: lo
    addresses:
      - fc10::1/128
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.4/24
      - fc00::4/64
    gateway4: 192.168.100.1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp3s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc24::2/64
    nameservers: {}
