version: 2
ethernets:
  enp1s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.2/24
      - fc00::2/64
    gateway4: 192.168.100.1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc23:1::1/64
    nameservers: {}
  enp3s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc23:2::1/64
    nameservers: {}
  enp4s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc24::1/64
    nameservers: {}
  enp5s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc25::1/64
    nameservers: {}
  enp6s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc26::1/64
    nameservers: {}
  enp7s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc27::1/64
    nameservers: {}
  enp8s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc28::1/64
    nameservers: {}
