version: 2
ethernets:
  ens2:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.2/24
      - fc00::2/64
    gateway4: 192.168.100.1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  ens3:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc30::1/64
    nameservers: {}
  ens4:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc31::1/64
    nameservers: {}
  ens5:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc40::1/64
    nameservers: {}
  ens6:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc50::1/64
    nameservers: {}
  ens7:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc60::1/64
    nameservers: {}
  ens8:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc70::1/64
    nameservers: {}
  ens9:
    dhcp4: false
    accept-ra: no
    addresses:
      - fc80::1/64
    nameservers: {}
