version: 2
ethernets:
  enp2s0:
    dhcp4: false
    accept-ra: no
    addresses:
      - 192.168.100.3/24
      - fc00::3/64
    gateway4: 192.168.100.1
    nameservers:
      addresses:
        - fc00::1
        - 192.168.100.1
      search: []
  enp3s0:
    dhcp4: false
    accept-ra: no
    mtu: 1460
    addresses:
      - fc23:1::2/64
    nameservers: {}
  enp4s0:
    dhcp4: false
    accept-ra: no
    mtu: 1460
    addresses:
      - fc23:2::2/64
    nameservers: {}
